[workspace]
authors = ["Eslam Allam <eslamallam73@gmail.com>"]
channels = ["conda-forge", "nvidia"]
name = "sentiment-analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[activation.env]
LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

[dependencies]
python = "3.12.*"
cuda = "12.3.*"
cudnn = "8.9.7.*"
scikit-learn = ">=1.8.0,<2"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
kagglehub = ">=1.0.0,<2"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
tensorflow = { version = ">=2.21.0, <3", extras = ["and-cuda"] }
opencv-python = ">=4.13.0.92, <5"
